/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Fabian.S
 */
public class ActionCentreMain extends javax.swing.JFrame {
    
    private PledgeManager pledgeManager;  //shared manager for all pledges
    
    //constructor used by MainApp
    public ActionCentreMain(PledgeManager pledgeManager) {
        initComponents();  //store reference to manager
        this.pledgeManager = pledgeManager;  //build GUI
        this.setLocationRelativeTo(null);  //keep windows on center
    }


    /**
     * Creates new form ActionCentreMain
     */
    public ActionCentreMain() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSubTitle = new javax.swing.JLabel();
        btnTipsLibrary = new javax.swing.JButton();
        btnPledgeForm = new javax.swing.JButton();
        btnImpactSummary = new javax.swing.JButton();
        btnMainMenu = new javax.swing.JButton();
        lblLearn = new javax.swing.JLabel();
        lblAct = new javax.swing.JLabel();
        lblSeeImpact = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Section 3: Action & Impact");

        lblSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubTitle.setText("Practical tools to turn learning into real-world conservation actions.");

        btnTipsLibrary.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnTipsLibrary.setText("Practical Tips");
        btnTipsLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipsLibraryActionPerformed(evt);
            }
        });

        btnPledgeForm.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnPledgeForm.setText("Make a Pledge");
        btnPledgeForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPledgeFormActionPerformed(evt);
            }
        });

        btnImpactSummary.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnImpactSummary.setText("Impact & Resources");
        btnImpactSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpactSummaryActionPerformed(evt);
            }
        });

        btnMainMenu.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnMainMenu.setText("Back to Main Menu");

        lblLearn.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblLearn.setText("Learn");

        lblAct.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblAct.setText("Act");

        lblSeeImpact.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblSeeImpact.setText("See your Impact");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(btnTipsLibrary)
                .addGap(18, 18, 18)
                .addComponent(btnPledgeForm)
                .addGap(18, 18, 18)
                .addComponent(btnImpactSummary)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(btnMainMenu)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lblLearn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAct)
                .addGap(94, 94, 94)
                .addComponent(lblSeeImpact)
                .addGap(54, 54, 54))
            .addComponent(lblSubTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubTitle)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLearn)
                    .addComponent(lblAct)
                    .addComponent(lblSeeImpact))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTipsLibrary)
                    .addComponent(btnPledgeForm)
                    .addComponent(btnImpactSummary))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(btnMainMenu)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTipsLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipsLibraryActionPerformed
        // TODO add your handling code here:
        TipsLibraryScreen tipsScreen = new TipsLibraryScreen(pledgeManager);
        tipsScreen.setVisible(true);
        this.dispose(); //closes ActionCentreMain
    }//GEN-LAST:event_btnTipsLibraryActionPerformed

    private void btnPledgeFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPledgeFormActionPerformed
        // TODO add your handling code here:
        
        PledgeFormScreen pledgeScreen = new PledgeFormScreen(pledgeManager);
        pledgeScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPledgeFormActionPerformed

    private void btnImpactSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpactSummaryActionPerformed
        // TODO add your handling code here:
        ImpactSummaryScreen impactScreen = new ImpactSummaryScreen(pledgeManager);
        impactScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnImpactSummaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActionCentreMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActionCentreMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActionCentreMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActionCentreMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActionCentreMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImpactSummary;
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JButton btnPledgeForm;
    private javax.swing.JButton btnTipsLibrary;
    private javax.swing.JLabel lblAct;
    private javax.swing.JLabel lblLearn;
    private javax.swing.JLabel lblSeeImpact;
    private javax.swing.JLabel lblSubTitle;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
