
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Fabian.S
 */
public class ImpactSummaryScreen extends javax.swing.JFrame {
    
    
    //shared pledgemanager so it can save pledges
    private PledgeManager pledgeManager; 
    
    public ImpactSummaryScreen(PledgeManager pledgeManager){
        this.pledgeManager = pledgeManager;
        initComponents();
        this.setLocationRelativeTo(null);
        refreshPledgeList();
    }

    /**
     * Creates new form ImpactSummaryScreen
     */
    public ImpactSummaryScreen() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    //updates the JList
    private void refreshPledgeList(){
        if (pledgeManager == null) return;
        
        ArrayList<Pledge> allPledges = pledgeManager.getAllPledge();
        DefaultListModel<String> model = new DefaultListModel<>();
        
        for (Pledge p : allPledges){
            model.addElement(p.toString()); 
        }
        
        lstPledges.setModel(model);
        
        //updating top stats
        int total = allPledges.size();
        lblTotalPledgesValue.setText("" + total);
        
        //estimate of plastic reduced
        double estimatedKg = total * 0.5;
        String formatted = String.format("%.1f", estimatedKg);
        lblPlasticReducedValue.setText("" + formatted);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblTotalPledgesTitle = new javax.swing.JLabel();
        lblTotalPledgesValue = new javax.swing.JLabel();
        lblPlasticReducedTitle = new javax.swing.JLabel();
        lblPlasticReducedValue = new javax.swing.JLabel();
        lblResourcesTitle = new javax.swing.JLabel();
        scrollLocalResources = new javax.swing.JScrollPane();
        txtLocalResources = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPledges = new javax.swing.JList<>();
        lblPledges = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        lblSearch = new javax.swing.JLabel();
        txtSearchName = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Your Impact & Next Steps");
        lblTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnBack.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTotalPledgesTitle.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblTotalPledgesTitle.setText("Total Pledges:");

        lblTotalPledgesValue.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblTotalPledgesValue.setText("0");

        lblPlasticReducedTitle.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblPlasticReducedTitle.setText("Estimated plastic reduced (kg):");

        lblPlasticReducedValue.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblPlasticReducedValue.setText("0.0");

        lblResourcesTitle.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblResourcesTitle.setText("Local Resources & Next Steps");

        txtLocalResources.setEditable(false);
        txtLocalResources.setColumns(20);
        txtLocalResources.setLineWrap(true);
        txtLocalResources.setRows(5);
        txtLocalResources.setText("• Join a local beach or river clean-up.\n\n• Visit nearby enviromental NGOs.\n\n• Start a plastic-free challenge with friends.\n\n• Share this app to inspire others to take action.");
        txtLocalResources.setWrapStyleWord(true);
        txtLocalResources.setMargin(new java.awt.Insets(5, 5, 5, 5));
        scrollLocalResources.setViewportView(txtLocalResources);

        lstPledges.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstPledges.setToolTipText("");
        jScrollPane1.setViewportView(lstPledges);

        lblPledges.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblPledges.setText("Your Pledges");

        btnDelete.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnDelete.setText("Delete Pledge");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblSearch.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblSearch.setText("Search By Name:");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollLocalResources, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotalPledgesTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalPledgesValue)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDelete))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(lblResourcesTitle))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblPlasticReducedTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPlasticReducedValue))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(lblPledges))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch)))
                        .addGap(0, 62, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalPledgesTitle)
                    .addComponent(lblTotalPledgesValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlasticReducedTitle)
                    .addComponent(lblPlasticReducedValue))
                .addGap(49, 49, 49)
                .addComponent(lblResourcesTitle)
                .addGap(18, 18, 18)
                .addComponent(scrollLocalResources, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lblPledges)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ActionCentreMain mainScreen = new ActionCentreMain(pledgeManager);
        mainScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String selected = lstPledges.getSelectedValue();
        
        if (selected == null){
            JOptionPane.showMessageDialog(this,
                    "Please select a pledge to delete.",
                    "No selection",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
        //extract full name: everything before " - ("
        int cutIndex = selected.indexOf(" - (");
        String name;
        if (cutIndex > 0){
            name = selected.substring(0, cutIndex).trim();
        } else {
            name = selected.trim(); //fallback
        }
       
        boolean removed = pledgeManager.removeByName(name);
        
        if (removed){
            JOptionPane.showMessageDialog(this,
                    "Pledge deleted successfully,",
                    "Deleted",
                    JOptionPane.INFORMATION_MESSAGE);
            refreshPledgeList(); //reload list
        } else {
            JOptionPane.showMessageDialog(this,
                    "Could not deleted pledge.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String name = txtSearchName.getText().trim();
        
        if (name.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(
            this,
                    "Please enter a name to serach.",
                    "No name entered",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
        //using pledgemanager search function
        Pledge found = pledgeManager.findByName(name);
        
        if (found == null) {
            javax.swing.JOptionPane.showMessageDialog(
            this,
                    "No pledge found for: " + name,
                    "Not found",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }
        
        //show the found pledge
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Pledge found:\n" + found.toString(),
                "Pledge found",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
        
        //highlist in the JList
        javax.swing.ListModel<String> model = lstPledges.getModel();
        int indexToSelect = -1;
        
        for (int i = 0; i < model.getSize(); i++) {
            String item = model.getElementAt(i);
            if (item.startsWith(found.getUserName()+ " - (:")) {
                indexToSelect = i;
                break;
            }
        }
        
        if (indexToSelect >= 0){
            lstPledges.setSelectedIndex(indexToSelect);
            lstPledges.ensureIndexIsVisible(indexToSelect);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImpactSummaryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImpactSummaryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImpactSummaryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImpactSummaryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImpactSummaryScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPlasticReducedTitle;
    private javax.swing.JLabel lblPlasticReducedValue;
    private javax.swing.JLabel lblPledges;
    private javax.swing.JLabel lblResourcesTitle;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalPledgesTitle;
    private javax.swing.JLabel lblTotalPledgesValue;
    private javax.swing.JList<String> lstPledges;
    private javax.swing.JScrollPane scrollLocalResources;
    private javax.swing.JTextArea txtLocalResources;
    private javax.swing.JTextField txtSearchName;
    // End of variables declaration//GEN-END:variables
}
