
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Fabian.S
 */
public class PledgeFormScreen extends javax.swing.JFrame {
    
    //shared pledgemanager so it can save pledges
    private PledgeManager pledgeManager;
    
    //constructor that receives the sharedf pledgeManager
    public PledgeFormScreen(PledgeManager pledgeManager){
        this.pledgeManager = pledgeManager;  //store the manager
        initComponents();  //build GUI
        this.setLocationRelativeTo(null);  //centre windows
    }

    /**
     * Creates new form PledgeFormScreen
     */
    public PledgeFormScreen() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblInstructions = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblActions = new javax.swing.JLabel();
        chkReuseBottle = new javax.swing.JCheckBox();
        chkReducePlasticBags = new javax.swing.JCheckBox();
        chkBeachCleanup = new javax.swing.JCheckBox();
        chkRecycleProperly = new javax.swing.JCheckBox();
        chkShareWithFriends = new javax.swing.JCheckBox();
        txtUserName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Make a Pledge");

        lblInstructions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstructions.setText("Choose one or more actions you're ready to commit to, and save your pledge");

        lblUserName.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblUserName.setText("Your name:");

        lblActions.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblActions.setText("Actions you will take:");

        chkReuseBottle.setText("Use a reusable water bottle");
        chkReuseBottle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkReuseBottleActionPerformed(evt);
            }
        });

        chkReducePlasticBags.setText("Avoid single-use plastic bags");

        chkBeachCleanup.setText("Join a local beach or river clean-up");

        chkRecycleProperly.setText("Sort and recycle plastic correctly");

        chkShareWithFriends.setText("Share these tips with friends/family");

        txtUserName.setMargin(new java.awt.Insets(2, 2, 2, 2));
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSubmit.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblDate.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblDate.setText("Date:");

        txtDate.setText("DD/MM/YYYY");
        txtDate.setMargin(new java.awt.Insets(2, 2, 2, 2));
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUserName)
                            .addComponent(lblDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUserName)
                            .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblActions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkReducePlasticBags)
                            .addComponent(chkReuseBottle)
                            .addComponent(chkBeachCleanup)
                            .addComponent(chkRecycleProperly)
                            .addComponent(chkShareWithFriends)))
                    .addComponent(btnSubmit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblInstructions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstructions)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActions)
                    .addComponent(chkReuseBottle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkReducePlasticBags)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkBeachCleanup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkRecycleProperly)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkShareWithFriends)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed
    
    //back button
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ActionCentreMain mainScreen = new ActionCentreMain(pledgeManager);
        mainScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed
    
    //submit button
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        //reads input
        String name = txtUserName.getText().trim();
        String date = txtDate.getText().trim();
        
        //build a list of selected actions
        ArrayList<String> actions = new ArrayList<>();
        
        if (chkReuseBottle.isSelected()){
            actions.add("User a reusable water bottle");
        }
        if (chkReducePlasticBags.isSelected()){
            actions.add("Avoid single-use plastic bags");
        }
        if (chkBeachCleanup.isSelected()){
            actions.add("Join a local beach or river clean-up");
        }
        if (chkRecycleProperly.isSelected()){
            actions.add("Sprt and recycle plastic correctly");
        }
        if (chkShareWithFriends.isSelected()){
            actions.add("Share these tips with friends/family");
        }
        
        //basic validation so empty or incomplete pledges are not saved
        if (name.isEmpty() || date.isEmpty() || actions.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(
            this,
                    "Please enter your name. date, and select at least one action",
                    "Missing information",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return; //stops here if form incomplete
        }
        
        //creates the pledge object
        Pledge newPledge = new Pledge(name, date, actions);
        
        //add the pledge to the shared pledgemanager
        if (pledgeManager != null) {
            pledgeManager.addPledge(newPledge);
        }
        
        //give feedback to the user
        javax.swing.JOptionPane.showMessageDialog(
        this,
                "Thank you! Your pledge has been saved,",
                "Pledge Submitted,",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
        
        //clear the form for next pledge
        txtUserName.setText("");
        txtDate.setText("DD/MM/YYYY");
        chkReuseBottle.setSelected(false);
        chkReducePlasticBags.setSelected(false);
        chkBeachCleanup.setSelected(false);
        chkRecycleProperly.setSelected(false);
        chkShareWithFriends.setSelected(false);       
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void chkReuseBottleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkReuseBottleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkReuseBottleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PledgeFormScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PledgeFormScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PledgeFormScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PledgeFormScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PledgeFormScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox chkBeachCleanup;
    private javax.swing.JCheckBox chkRecycleProperly;
    private javax.swing.JCheckBox chkReducePlasticBags;
    private javax.swing.JCheckBox chkReuseBottle;
    private javax.swing.JCheckBox chkShareWithFriends;
    private javax.swing.JLabel lblActions;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblInstructions;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
