
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Fabian.S
 */
public class TipsLibraryScreen extends javax.swing.JFrame {
    
    //shared pledgemanager so it can save pledges
    private PledgeManager pledgeManager;
    
    //declaring arraylist
    private ArrayList<Tip> tips = new ArrayList<>();

    /**z
     * Creates new form TipsLibraryScreen
     */
    //constructor
    public TipsLibraryScreen(PledgeManager pledgeManager) {
        this.pledgeManager = pledgeManager; //store shared manager
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        loadTips();  //loads tips into arraylist
        refreshTipList();  //shows them in JList
        txtTipDetails.setEditable(false);  //stop users typing here
        
        lstTips.addListSelectionListener(new javax.swing.event.ListSelectionListener(){
            @Override
            public void valueChanged(javax.swing.event.ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int index = lstTips.getSelectedIndex();
                    if( index >= 0) {
                        Tip selected = tips.get(index);
                        lblCategoryTitle.setText("Category: " + selected.getCategory());
                        txtTipDetails.setText(selected.getDetails());
                    }
                }
            }
        });   
    }

    private void loadTips(){
        tips.clear();
        
        tips.add(new Tip(
                "Use a reusable bottle",
                "Daily Habits",
                "Swap single-use plastic bottles for a reusable one. "
              + "Carry it with you to school, work, and trips to cut plastic waste"
        ));
        
        tips.add(new Tip(
                "Avoid single-use plastic bags",
                "Shopping",
                "Bring your own reusable bag when shopping "
              + "Keep a foldable bag in your backpack so you never forget."
        ));
        
        tips.add(new Tip(
                "Choose plastic-free snacks",
                "Food Choices",
                "Pick snacks with minimal or recyclable packaging. "
              + "Buy a bigger packs and portion thenm yourself instead of many small plastic wrappers."
        ));
        
        tips.add(new Tip(
                "Join a local clean-up",
                "Community Action",
                "Look for beach, river, or park clean-ups in your area. "
              + "Invite friends to join and turn it into a regular event."
        ));
        
        tips.add(new Tip(
                "Support sustainable seafood",
                "Food choices",
                "Choose seafood from sustainable sources and avoid overfished species. "
              + "Look for eco-labels or ask your fishmonger for advice."
        ));     
    }
    
    //refresh JList
    private void refreshTipList(){
        DefaultListModel<String> model = new DefaultListModel<>();
        for (Tip t : tips) {
            model.addElement(t.getTitle()); //only shows the title in the list
        }
        lstTips.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        scrollTips = new javax.swing.JScrollPane();
        lstTips = new javax.swing.JList<>();
        btnBack = new javax.swing.JButton();
        lblInstructions = new javax.swing.JLabel();
        lblTitleTips = new javax.swing.JLabel();
        scrollTipDetails = new javax.swing.JScrollPane();
        txtTipDetails = new javax.swing.JTextArea();
        lblTipsDetailsTitle = new javax.swing.JLabel();
        lblCategoryTitle = new javax.swing.JLabel();
        lblCategoryValue = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Practical Tips Library");

        lstTips.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1. Use a reusable bottle", "2. Avoid single-use plastic bags", "3. Choose plastic-free snacks", "4. Join a local clean-up", "5. Support sustaianble seafood" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstTips.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstTipsValueChanged(evt);
            }
        });
        scrollTips.setViewportView(lstTips);

        btnBack.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblInstructions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstructions.setText("Browse quick tips for reducing plastic use and protecting marine life.");

        lblTitleTips.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblTitleTips.setText("Tips");

        txtTipDetails.setEditable(false);
        txtTipDetails.setColumns(20);
        txtTipDetails.setLineWrap(true);
        txtTipDetails.setRows(5);
        txtTipDetails.setText("Select a tip on the left to view:\n\n• A short explanation of why this action matters.\n• Simple steps to put it into practice.\n• The category it belongs to.");
        txtTipDetails.setWrapStyleWord(true);
        txtTipDetails.setMargin(new java.awt.Insets(5, 5, 5, 5));
        scrollTipDetails.setViewportView(txtTipDetails);

        lblTipsDetailsTitle.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblTipsDetailsTitle.setText("Tip Details");

        lblCategoryTitle.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblCategoryTitle.setText("Category:");

        lblCategoryValue.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("Select a tip to view more details.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInstructions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollTips, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(lblTitleTips))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCategoryTitle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCategoryValue))
                                    .addComponent(lblTipsDetailsTitle))
                                .addGap(212, 212, 212))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(scrollTipDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstructions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCategoryTitle)
                        .addComponent(lblCategoryValue))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitleTips)
                            .addComponent(lblTipsDetailsTitle))
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollTipDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(scrollTips, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addComponent(btnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ActionCentreMain mainScreen = new ActionCentreMain(pledgeManager);
        mainScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void lstTipsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstTipsValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lstTipsValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipsLibraryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipsLibraryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipsLibraryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipsLibraryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TipsLibraryScreen(new PledgeManager()).setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCategoryTitle;
    private javax.swing.JLabel lblCategoryValue;
    private javax.swing.JLabel lblInstructions;
    private javax.swing.JLabel lblTipsDetailsTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleTips;
    private javax.swing.JList<String> lstTips;
    private javax.swing.JScrollPane scrollTipDetails;
    private javax.swing.JScrollPane scrollTips;
    private javax.swing.JTextArea txtTipDetails;
    // End of variables declaration//GEN-END:variables
}
